---
vmDefaults:
  cloudInitSecret: secret/data/hub/cloud-init
  accessMode: "ReadWriteOnce"
  storageClassName: "gp3-csi"
  volumeMode: "Block"
  count: 1
  flavor: medium
  workload: server
  os: rhel9
  storage: 30Gi
  memory: 8Gi
  machineType: pc-q35-rhel8.4.0
  cores: 1
  sockets: 1
  threads: 4
  template: rhel9-server-medium
  sshsecret: secret/data/hub/vm-ssh
  cloudinitsecret: secret/data/hub/cloud-init
  sshpubkeyfield: publickey
  serviceType: LoadBalancer
  # extraLabels is available for default extra labels to add to the virtualmachine
  # extraAnnotations is available for default extra labels to add to the virtualmachine
  ports:
    - name: ssh
      port: 22
      protocol: TCP
      targetPort: 22
    - name: receptor
      port: 27199
      protocol: TCP
      targetPort: 27199
    - name: openvpn
      port: 1194
      protocol: TCP
      targetPort: 1194
    - name: ipsec
      port: 4500
      protocol: TCP
      targetPort: 4500

vms:
  vpn:
    count: 1
    role: vpn
    routes:
      - name: vpn-endpoint
        targetPort: 1194
