---
clusterGroup:
  name: hub
  isHubCluster: true

  namespaces:
    - vault
    - golang-external-secrets
    - ansible-automation-platform
    - aap-config
    - openshift-cnv
    - edge-gitops-vms
    - edge-observability-stack
    - open-cluster-management
    - external-dns-operator

  subscriptions:
    aap-operator:
      name: ansible-automation-platform-operator
      namespace: ansible-automation-platform
      channel: stable-2.5

    acm:
      name: advanced-cluster-management
      namespace: open-cluster-management
      channel: release-2.13

    external-dns:
      name: external-dns-operator
      namespace: external-dns-operator
      channel: stable-v1

    openshift-virtualization:
      name: kubevirt-hyperconverged
      namespace: openshift-cnv
      channel: stable

  projects:
    - hub

  imperative:
    jobs:
      - name: deploy-kubevirt-worker
        playbook: ansible/deploy_kubevirt_worker.yml
        verbosity: -vvv
    clusterRoleYaml:
      - apiGroups:
          - "*"
        resources:
          - machinesets
        verbs:
          - "*"
      - apiGroups:
          - "*"
        resources:
          - "*"
        verbs:
          - get
          - list
          - watch

  applications:
    aap:
      name: ansible-automation-platform
      namespace: ansible-automation-platform
      project: hub
      chart: ansible-automation-platform-instance
      chartVersion: 0.1.*
      overrides:
        - name: eePullSecret.manage
          value: "true"

    aap-config:
      name: aap-config
      namespace: aap-config
      project: hub
      chart: aap-config
      chartVersion: 0.1.*
      extraValueFiles:
        - '$patternref/overrides/values-aap-config-feo.yaml'

    acm:
      name: acm
      namespace: open-cluster-management
      project: hub
      #chart: acm
      repoURL: https://github.com/mhjacks/acm-chart
      chartVersion: main
      path: "."
      ignoreDifferences:
        - group: internal.open-cluster-management.io
          kind: ManagedClusterInfo
          jsonPointers:
            - /spec/loggingCA
      overrides:
        - name: edgeManager.enable
          value: "true"

    vault:
      name: vault
      namespace: vault
      project: hub
      chart: hashicorp-vault
      chartVersion: 0.1.*

    golang-external-secrets:
      name: golang-external-secrets
      namespace: golang-external-secrets
      project: hub
      chart: golang-external-secrets
      chartVersion: 0.1.*

    openshift-cnv:
      name: openshift-cnv
      namespace: openshift-cnv
      project: hub
      chart: openshift-virtualization-instance
      chartVersion: 0.1.*

    edge-gitops-vms:
      name: edge-gitops-vms
      namespace: edge-gitops-vms
      project: hub
      chart: edge-gitops-vms
      chartVersion: 0.2.*
      extraValueFiles:
        - '$patternref/overrides/values-egv-feo-vpn.yaml'

    edge-observability-stack:
      name: edge-observability-stack
      namespace: edge-observability-stack
      project: hub
      repoURL: https://github.com/validatedpatterns-demos/edge-observability-stack
      chartVersion: main
      path: "."

    ensure-openshift-console-plugins:
      name: ensure-openshift-console-plugins
      namespace: openshift-console
      project: hub
      chart: ensure-openshift-console-plugins
      chartVersion: 0.1.*
      extraValueFiles:
        - '$patternref/overrides/values-eocp-feo-vpn.yaml'

    external-dns-operator:
      name: external-dns-operator
      namespace: external-dns-operator
      project: hub
      chart: external-dns-operator
      chartVersion: 0.1.*

  # Only the hub cluster here - managed entities are edge nodes
  managedClusterGroups: []
